apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-mem-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic-deployment
  metrics:
  - type: Utilization # Specify the type as Utilization
    resource:
      name: memory # Target memory usage
      target: # Define the target object
        type: Utilization # Utilization target again
        averageUtilization: 80 # Set the desired average memory utilization (80%)
